# Generated by Django 4.0.1 on 2022-01-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=1)),
                ('query', models.TextField(blank=True)),
            ],
        ),
    ]
