# Generated by Django 4.0.1 on 2022-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0002_remove_person_branch_remove_person_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
