# Generated by Django 4.0.1 on 2022-03-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_form', '0003_alter_person_message_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
